[workspace]
members = [
  "./editions/aoc-2020",
  "./editions/aoc-2021",
  "./editions/aoc-2022",
  "./editions/aoc-2023",
  "./editions/aoc-2024",
  "./editions/aoc-2025",
  "./toolkit/aoc-sx",
  "./toolkit/aoc-sx-algo",
  "./toolkit/aoc-sx-cli",
  "./toolkit/aoc-sx-codegen",
  "./toolkit/aoc-sx-core",
  "./toolkit/aoc-sx-ui",
  "./toolkit/aoc-sx-webclient",
]
resolver = "2"

[workspace.dependencies]
# Image handling
image = "0.25.9"
# To create "heredocuments"
indoc = "2.0.7"
# Additional iterator methods
itertools = "0.14.0"
# Literal hashmaps and hashsets
maplit = "1.0.2"
# Numeric types and traits
num = "0.4.3"
# Lazy static values
once_cell = "1.21.3"
# Graph library
petgraph = "0.8.3"
# Regular expressions
regex = "1.12.2"
# Scrap HTML pages
scraper = "0.24.0"
# Serialization/deserialization
serde = { version = "1.0.228", features = ["derive"] }
# Serde on plain strings
serde_plain = "1.0.2"
# Pipelines everywhere!
tap = "1.0.1"
# Error creation
thiserror = "2.0.17"
# Logs and spans
tracing = "0.1.43"
# URL handling
url = "2.5.7"
